"""Global pytest fixtures for the Trackify automation suite."""

from __future__ import annotations

import json
import os
import re
import subprocess
import warnings
from collections.abc import Generator
from dataclasses import asdict
from pathlib import Path
from typing import Any

import allure
import pytest

from ai.triage import (
    MAX_RESULT_TEXT_LENGTH,
    SCHEMA_VERSION,
    TriageResult,
    redact_sensitive_text,
    triage_failure,
)
from flow.add_transaction_flow import AddTransactionFlow
from flow.app_setup_flow import AppSetupFlow
from flow.transactions_flow import TransactionsFlow
from page.add_transaction_page import AddTransactionPage
from page.home_page import HomePage
from page.onboarding_page import OnboardingPage
from page.transactions_page import TransactionsPage
from utils.environment_profile import (
    SUPPORTED_ENVIRONMENTS,
    EnvironmentProfile,
    load_environment_profile,
    resolve_environment,
)

PKG = os.getenv("ANDROID_PACKAGE", "com.blixcode.trackify")
IOS_BUNDLE_ID = os.getenv("IOS_BUNDLE_ID", "com.blixcode.trackify")
pytest_plugins = ("tests.step_defs.common_steps",)
PROJECT_ROOT = Path(__file__).resolve().parent
SCREENSHOT_DIR = Path(
    os.getenv("SCREENSHOT_DIR", PROJECT_ROOT / "report" / "screenshots")
).expanduser()
_SAFE_FILENAME_PATTERN = re.compile(r"[^A-Za-z0-9_.-]+")
_TRIAGED_FAILURE = pytest.StashKey[bool]()


def pytest_addoption(parser: pytest.Parser) -> None:
    """Register the environment selector used by direct pytest runs."""
    parser.addoption(
        "--env",
        action="store",
        dest="trackify_environment",
        choices=SUPPORTED_ENVIRONMENTS,
        default=None,
        help="Target environment profile (default: TEST_ENV or preprod).",
    )


class FeatureFile(pytest.File):
    """Proxy explicit .feature paths to their pytest-bdd step module."""

    def collect(self) -> list[pytest.Item]:
        """Collect tests generated by the matching step definition module.

        Returns:
            Test items from the matching ``tests/step_defs/*_steps.py`` file.
        """
        step_path = (
            self.path.parent.parent
            / "step_defs"
            / f"{self.path.stem}_steps.py"
        )
        if not step_path.exists():
            raise pytest.UsageError(f"No step definition module found for {self.path}")

        module = pytest.Module.from_parent(self, path=step_path)
        return list(module.collect())


def pytest_collect_file(
    file_path: Path,
    parent: pytest.Collector,
) -> FeatureFile | None:
    """Collect .feature files only when explicitly passed on the CLI.

    Args:
        file_path: Candidate file path.
        parent: Parent pytest collector.

    Returns:
        A feature proxy collector when the path was explicit, otherwise None.
    """
    if file_path.suffix != ".feature":
        return None

    explicit_features = {
        Path(arg).resolve()
        for arg in parent.config.args
        if str(arg).endswith(".feature")
    }
    if file_path.resolve() not in explicit_features:
        return None

    return FeatureFile.from_parent(parent, path=file_path)


def pytest_bdd_before_scenario(
    request: pytest.FixtureRequest,
    feature: Any,
    scenario: Any,
) -> None:
    """Expose readable BDD feature and scenario names in Allure results."""
    allure.dynamic.title(scenario.name)
    allure.dynamic.feature(feature.name)


def pytest_runtest_setup(item: pytest.Item) -> None:
    """Add matrix identity before fixtures so setup failures remain attributable."""
    del item
    context = _execution_context()
    allure.dynamic.parent_suite(context["environment"])
    allure.dynamic.suite(f"{context['platform']} - {context['device_name']}")
    allure.dynamic.label("host", context["device_udid"])
    allure.dynamic.parameter("Environment", context["environment"])
    allure.dynamic.parameter("Platform", context["platform"])
    allure.dynamic.parameter("Device", context["device_name"])
    allure.dynamic.parameter("OS Version", context["os_version"])
    allure.dynamic.parameter("UDID", context["device_udid"])


@pytest.hookimpl(tryfirst=True, hookwrapper=True)
def pytest_runtest_makereport(
    item: pytest.Item,
    call: pytest.CallInfo[Any],
) -> Generator[None, Any, None]:
    """Capture call failures and triage the first failed test phase."""
    outcome = yield
    report = outcome.get_result()
    if report.failed and call.excinfo is not None:
        screenshot_path = (
            _capture_failure_screenshot(item) if report.when == "call" else None
        )
        _triage_first_failure(item, call, report, screenshot_path)


def _triage_first_failure(
    item: pytest.Item,
    call: pytest.CallInfo[Any],
    report: pytest.TestReport,
    screenshot_path: Path | None,
) -> None:
    """Attach and print one advisory triage result for the first failed phase."""
    if item.stash.get(_TRIAGED_FAILURE, False):
        return
    item.stash[_TRIAGED_FAILURE] = True

    try:
        result = triage_failure(
            {
                "error_msg": str(call.excinfo.value),
                "traceback": str(call.excinfo.getrepr(style="long")),
                "test_name": item.nodeid,
                "phase": report.when,
                "screenshot_path": screenshot_path,
            }
        )
    except Exception:
        result = TriageResult(
            category="Unknown",
            confidence=0.0,
            reasoning="Failure triage raised an internal error.",
            next_action="Review the original failure and reporting diagnostics.",
            classifier="disabled",
            matched_signatures=(),
        )

    safe_test_name = redact_sensitive_text(item.nodeid)[:MAX_RESULT_TEXT_LENGTH]
    attachment = {
        "schema_version": SCHEMA_VERSION,
        "test_name": safe_test_name,
        "phase": report.when,
        **asdict(result),
    }
    try:
        allure.attach(
            json.dumps(attachment, indent=2, ensure_ascii=True),
            name="AI Triage",
            attachment_type=allure.attachment_type.JSON,
        )
    except Exception as exc:
        warnings.warn(
            pytest.PytestWarning(f"Could not attach AI Triage result: {exc}"),
            stacklevel=1,
        )

    line = (
        f"[AI Triage] {result.category} ({result.confidence:.0%}): "
        f"{result.reasoning}"
    )
    try:
        terminal_reporter = item.config.pluginmanager.getplugin("terminalreporter")
        if terminal_reporter is not None:
            terminal_reporter.write_line(line)
        else:
            print(line)
    except Exception as exc:
        warnings.warn(
            pytest.PytestWarning(f"Could not print AI Triage result: {exc}"),
            stacklevel=1,
        )


def _capture_failure_screenshot(item: pytest.Item) -> Path | None:
    driver = item.funcargs.get("driver")
    if driver is None:
        warnings.warn(
            pytest.PytestWarning(
                f"Cannot capture {item.name!r}: driver fixture is unavailable."
            ),
            stacklevel=1,
        )
        return None

    safe_test_name = _SAFE_FILENAME_PATTERN.sub("_", item.name).strip("._")
    screenshot_path = SCREENSHOT_DIR / f"{safe_test_name}.png"
    screenshot_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        saved = driver.save_screenshot(str(screenshot_path))
        if saved is False:
            raise RuntimeError("Appium returned false while saving the screenshot.")
        allure.attach.file(
            str(screenshot_path),
            name=f"Failure screenshot - {item.name}",
            attachment_type=allure.attachment_type.PNG,
        )
    except Exception as exc:
        warnings.warn(
            pytest.PytestWarning(
                f"Could not capture failure screenshot for {item.name!r}: {exc}"
            ),
            stacklevel=1,
        )
        return None
    return screenshot_path


@pytest.fixture(scope="session")
def environment_profile(pytestconfig: pytest.Config) -> EnvironmentProfile:
    """Load the selected environment before any Appium session is created."""
    environment = resolve_environment(
        pytestconfig.getoption("trackify_environment"),
        os.environ,
    )
    return load_environment_profile(environment)


@pytest.fixture(scope="session")
def driver(
    pytestconfig: pytest.Config,
    environment_profile: EnvironmentProfile,
) -> Generator[Any, None, None]:
    """Create one Appium driver session for the pytest run.

    Yields:
        The live Appium driver instance created by ``AppiumDriverFactory``.
    """
    from utils.driver import AppiumDriverFactory

    del environment_profile
    platform = os.getenv("PLATFORM", "android")
    appium_driver = AppiumDriverFactory(platform=platform).create()
    _write_allure_environment(pytestconfig, appium_driver)
    try:
        yield appium_driver
    finally:
        appium_driver.quit()


@pytest.fixture(autouse=True)
def reset_app_state(request: pytest.FixtureRequest) -> Generator[None, None, None]:
    """Wipe Trackify local data before every test for deterministic state.

    Args:
        request: Current pytest request, used to isolate unit tests from Appium.

    Yields:
        None after relaunching the app under test.
    """
    if request.node.get_closest_marker("unit") is not None:
        yield
        return

    driver = request.getfixturevalue("driver")
    platform = str(driver.capabilities.get("platformName", "")).lower()
    app_id = IOS_BUNDLE_ID if platform == "ios" else PKG

    if platform == "ios":
        if os.getenv("IOS_REAL_DEVICE", "false").lower() == "true":
            driver.execute_script("mobile: removeApp", {"bundleId": app_id})
            driver.execute_script(
                "mobile: installApp", {"app": str(Path(os.environ["APP_PATH"]).resolve())}
            )
        else:
            driver.execute_script("mobile: clearApp", {"bundleId": app_id})
    else:
        adb_command = [_adb()]
        if device_udid := os.getenv("DEVICE_UDID"):
            adb_command.extend(["-s", device_udid])
        subprocess.run(
            [*adb_command, "shell", "pm", "clear", app_id],
            check=True,
            timeout=10,
        )

    if hasattr(driver, "activate_app"):
        driver.activate_app(app_id)
    else:
        driver.launch_app()
    yield


@pytest.fixture
def home_page(driver: Any) -> HomePage:
    """Create a Home page object for the current test.

    Args:
        driver: The active Appium driver fixture.

    Returns:
        Home page object bound to the active driver.
    """
    return HomePage(driver)


@pytest.fixture
def onboarding_page(driver: Any) -> OnboardingPage:
    """Create an onboarding page object for the current test.

    Args:
        driver: The active Appium driver fixture.

    Returns:
        Onboarding page object bound to the active driver.
    """
    return OnboardingPage(driver)


@pytest.fixture
def add_transaction_page(driver: Any) -> AddTransactionPage:
    """Create an Add Transaction page object for the current test.

    Args:
        driver: The active Appium driver fixture.

    Returns:
        Add Transaction page object bound to the active driver.
    """
    return AddTransactionPage(driver)


@pytest.fixture
def transactions_page(driver: Any) -> TransactionsPage:
    """Create a Transactions page object for the current test.

    Args:
        driver: The active Appium driver fixture.

    Returns:
        Transactions page object bound to the active driver.
    """
    return TransactionsPage(driver)


@pytest.fixture
def app_setup_flow(
    onboarding_page: OnboardingPage,
    home_page: HomePage,
) -> AppSetupFlow:
    """Create the ordered first-run setup flow for the current test.

    Args:
        onboarding_page: Onboarding page fixture.
        home_page: Home page fixture.

    Returns:
        Flow object for the three required setup stages.
    """
    return AppSetupFlow(onboarding_page, home_page)


@pytest.fixture
def add_transaction_flow(
    home_page: HomePage,
    add_transaction_page: AddTransactionPage,
    transactions_page: TransactionsPage,
) -> AddTransactionFlow:
    """Create an Add Transaction flow for the current test.

    Args:
        home_page: Home page fixture.
        add_transaction_page: Add Transaction page fixture.
        transactions_page: Transactions page fixture.

    Returns:
        Flow object composed from page fixtures.
    """
    return AddTransactionFlow(home_page, add_transaction_page, transactions_page)


@pytest.fixture
def transactions_flow(transactions_page: TransactionsPage) -> TransactionsFlow:
    """Create a Transactions business flow for the current test.

    Args:
        transactions_page: Transactions page fixture.

    Returns:
        Flow object for filtering and verifying transaction groups.
    """
    return TransactionsFlow(transactions_page)


def _adb() -> str:
    sdk_root = os.getenv("ANDROID_HOME") or os.getenv("ANDROID_SDK_ROOT")
    candidates = []
    if sdk_root:
        candidates.append(Path(sdk_root) / "platform-tools" / "adb")
    candidates.append(
        Path.home() / "Library" / "Android" / "sdk" / "platform-tools" / "adb"
    )

    for candidate in candidates:
        if candidate.exists():
            return str(candidate)
    return "adb"


def _execution_context(driver: Any | None = None) -> dict[str, str]:
    capabilities = getattr(driver, "capabilities", {}) if driver is not None else {}
    platform = str(capabilities.get("platformName") or os.getenv("PLATFORM", "unknown"))
    device_name = str(
        os.getenv("DEVICE_NAME")
        or capabilities.get("deviceName")
        or capabilities.get("appium:deviceName")
        or "unknown"
    )
    device_udid = str(
        os.getenv("DEVICE_UDID")
        or capabilities.get("udid")
        or capabilities.get("appium:udid")
        or "unknown"
    )
    os_version = str(
        os.getenv("OS_VERSION")
        or capabilities.get("platformVersion")
        or capabilities.get("appium:platformVersion")
        or "unknown"
    )
    return {
        "environment": os.getenv("TEST_ENV", "preprod"),
        "platform": platform,
        "device_name": device_name,
        "device_udid": device_udid,
        "os_version": os_version,
    }


def _write_allure_environment(pytestconfig: pytest.Config, driver: Any) -> None:
    report_dir = os.getenv("ALLURE_RESULTS_DIR") or getattr(
        pytestconfig.option, "allure_report_dir", None
    )
    if not report_dir:
        return
    output_dir = Path(report_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    context = _execution_context(driver)
    properties = "\n".join(
        f"{key}={value}"
        for key, value in (
            ("Test.Environment", context["environment"]),
            ("Device.Platform", context["platform"]),
            ("Device.Name", context["device_name"]),
            ("Device.UDID", context["device_udid"]),
            ("Device.OS.Version", context["os_version"]),
        )
    )
    (output_dir / "environment.properties").write_text(
        f"{properties}\n", encoding="utf-8"
    )


def pytest_sessionfinish(
    session: pytest.Session,
    exitstatus: int | pytest.ExitCode,
) -> None:
    """Allow bootstrap collect-only verification before test files exist.

    Args:
        session: Completed pytest session.
        exitstatus: Pytest exit status before this hook adjusts it.
    """
    if (
        session.config.option.collectonly
        and exitstatus == pytest.ExitCode.NO_TESTS_COLLECTED
    ):
        session.exitstatus = pytest.ExitCode.OK
