"""Global pytest fixtures for the Trackify automation suite."""

from __future__ import annotations

import os
import subprocess
from collections.abc import Generator
from pathlib import Path
from typing import Any

import pytest

from flow.add_transaction_flow import AddTransactionFlow
from flow.app_setup_flow import AppSetupFlow
from page.add_transaction_page import AddTransactionPage
from page.home_page import HomePage
from page.onboarding_page import OnboardingPage

PKG = os.getenv("ANDROID_PACKAGE", "com.blixcode.trackify")


class FeatureFile(pytest.File):
    """Proxy explicit .feature paths to their pytest-bdd step module."""

    def collect(self) -> list[pytest.Item]:
        """Collect tests generated by the matching step definition module.

        Returns:
            Test items from the matching ``tests/step_defs/*_steps.py`` file.
        """
        step_path = (
            self.path.parent.parent
            / "step_defs"
            / f"{self.path.stem}_steps.py"
        )
        if not step_path.exists():
            raise pytest.UsageError(f"No step definition module found for {self.path}")

        module = pytest.Module.from_parent(self, path=step_path)
        return list(module.collect())


def pytest_collect_file(
    file_path: Path,
    parent: pytest.Collector,
) -> FeatureFile | None:
    """Collect .feature files only when explicitly passed on the CLI.

    Args:
        file_path: Candidate file path.
        parent: Parent pytest collector.

    Returns:
        A feature proxy collector when the path was explicit, otherwise None.
    """
    if file_path.suffix != ".feature":
        return None

    explicit_features = {
        Path(arg).resolve()
        for arg in parent.config.args
        if str(arg).endswith(".feature")
    }
    if file_path.resolve() not in explicit_features:
        return None

    return FeatureFile.from_parent(parent, path=file_path)


@pytest.fixture(scope="session")
def driver() -> Generator[Any, None, None]:
    """Create one Appium driver session for the pytest run.

    Yields:
        The live Appium driver instance created by ``AppiumDriverFactory``.
    """
    from utils.driver import AppiumDriverFactory

    platform = os.getenv("PLATFORM", "android")
    appium_driver = AppiumDriverFactory(platform=platform).create()
    try:
        yield appium_driver
    finally:
        appium_driver.quit()


@pytest.fixture(autouse=True)
def reset_app_state(driver: Any) -> Generator[None, None, None]:
    """Wipe Trackify local data before every test for deterministic state.

    Args:
        driver: The active Appium driver fixture.

    Yields:
        None after relaunching the app under test.
    """
    subprocess.run([_adb(), "shell", "pm", "clear", PKG], check=True, timeout=10)
    if hasattr(driver, "activate_app"):
        driver.activate_app(PKG)
    else:
        driver.launch_app()
    yield


@pytest.fixture
def home_page(driver: Any) -> HomePage:
    """Create a Home page object for the current test.

    Args:
        driver: The active Appium driver fixture.

    Returns:
        Home page object bound to the active driver.
    """
    return HomePage(driver)


@pytest.fixture
def onboarding_page(driver: Any) -> OnboardingPage:
    """Create an onboarding page object for the current test.

    Args:
        driver: The active Appium driver fixture.

    Returns:
        Onboarding page object bound to the active driver.
    """
    return OnboardingPage(driver)


@pytest.fixture
def add_transaction_page(driver: Any) -> AddTransactionPage:
    """Create an Add Transaction page object for the current test.

    Args:
        driver: The active Appium driver fixture.

    Returns:
        Add Transaction page object bound to the active driver.
    """
    return AddTransactionPage(driver)


@pytest.fixture
def app_setup_flow(
    onboarding_page: OnboardingPage,
    home_page: HomePage,
) -> AppSetupFlow:
    """Create the ordered first-run setup flow for the current test.

    Args:
        onboarding_page: Onboarding page fixture.
        home_page: Home page fixture.

    Returns:
        Flow object for the three required setup stages.
    """
    return AppSetupFlow(onboarding_page, home_page)


@pytest.fixture
def add_transaction_flow(
    home_page: HomePage,
    add_transaction_page: AddTransactionPage,
) -> AddTransactionFlow:
    """Create an Add Transaction flow for the current test.

    Args:
        home_page: Home page fixture.
        add_transaction_page: Add Transaction page fixture.

    Returns:
        Flow object composed from page fixtures.
    """
    return AddTransactionFlow(home_page, add_transaction_page)


def _adb() -> str:
    sdk_root = os.getenv("ANDROID_HOME") or os.getenv("ANDROID_SDK_ROOT")
    candidates = []
    if sdk_root:
        candidates.append(Path(sdk_root) / "platform-tools" / "adb")
    candidates.append(
        Path.home() / "Library" / "Android" / "sdk" / "platform-tools" / "adb"
    )

    for candidate in candidates:
        if candidate.exists():
            return str(candidate)
    return "adb"


def pytest_sessionfinish(
    session: pytest.Session,
    exitstatus: int | pytest.ExitCode,
) -> None:
    """Allow bootstrap collect-only verification before test files exist.

    Args:
        session: Completed pytest session.
        exitstatus: Pytest exit status before this hook adjusts it.
    """
    if (
        session.config.option.collectonly
        and exitstatus == pytest.ExitCode.NO_TESTS_COLLECTED
    ):
        session.exitstatus = pytest.ExitCode.OK
